// src/components/QuizNavbar.vue
<script setup lang="ts">
import Button from '@/components/Button.vue'
import Container from '@/components/layout/Container.vue'
import AnimatedSection from '@/components/layout/AnimatedSection.vue'
import {useRoute, useRouter} from "vue-router";
import { useQuizStore } from '@/stores/quiz'
import { computed } from 'vue';

const router = useRouter()
const route = useRoute()
const store = useQuizStore()

function next() {
  if (store.state === 'result') {
    router.push({name: 'home'})
  } else if (!store.hasRespondedCurrentQuestion) {
    store.saveAnswer(store.selectedIndex)
  } else if (store.hasNextIndex) {
    store.index++
    store.selectedIndex = -1
  } else {
    store.state = "result"
  }
}

const canNext = computed(() => {
  console.log(store.state, store.selectedIndex)
  if (store.state === 'quiz' && store.selectedIndex === -1) return false
  else return true
})
</script>

<template>
  <div class="bg-gray-800 bg-opacity-50 p-4 grid gap-4">
    <div class="grid items-center" style="grid-template-columns: 1fr auto">
      <div v-if="store.state ==='quiz'" class="relative h-full">
        <AnimatedSection
          v-for="(question, index) in store.questions" 
          :key="`question-description-${index}`"
          :show="store.index === index && store.state === 'quiz'"
          class="flex items-center"
        >
          {{ question.description }}
        </AnimatedSection>
      </div>
      <div class="justify-self-center">
        <Button 
          @click="next"
          class="transition-all" 
          :class="{'opacity-50 pointer-events-none': !canNext}"
        >
          <template v-if="store.state === 'quiz'">Suivant</template>
          <template v-if="store.state === 'result'">Page d'accueil</template>
        </Button>
      </div>
    </div>
  </div>
</template>

// src/components/QuizNavbar.tsx

import { Button } from '~/components/Button'
import { AnimatedSection } from '~/components/layout/AnimatedSection'
import { Component, For, Show, useContext } from 'solid-js';
import classNames from 'classnames'
import { QuizContext } from '~/routes/quiz/[id]';
import { useNavigate } from 'solid-start';

export const QuizNavbar: Component = () => {
  const navigate = useNavigate()
  const {state, setState, saveAnswer, hasRespondedCurrentQuestion, hasNextIndex} = useContext(QuizContext);

  function next() {
    if (state.state === 'result') {
      navigate('/home')
    } else if (!hasRespondedCurrentQuestion()) {
      saveAnswer(state.selectedIndex)
    } else if (hasNextIndex()) {
      setState({
        index: state.index + 1,
        selectedIndex: -1
      })
    } else {
      setState({
        state: "result"
      })
    }
  }

  const canNext = () => {
    if (state.state === 'quiz' && state.selectedIndex === -1) return false
    else return true
  }

  return <div class="bg-gray-800 bg-opacity-50 p-4 grid gap-4">
    <div class="grid items-center" style="grid-template-columns: 1fr auto">
      <div v-if="store.state ==='quiz'" class="relative h-full">
        <For each={state.questions}>
          {(question, index) => <AnimatedSection
            show={state.index === index() && state.state === 'quiz'}
            class="flex items-center"
          >
            {question.description}
          </AnimatedSection>}
        </For>
      </div>
      <div class="justify-self-center">
        <Button 
          class={classNames({'opacity-50 pointer-events-none': !canNext(), 'transition-all': true})}
          onClick={next}
        >
          <Show when={state.state === 'quiz'}>Suivant</Show>
          <Show when={state.state === 'result'}>Page d'accueil</Show>
        </Button>
      </div>
    </div>
  </div>
}
