// src/components/Quiz.vue
<script setup lang="ts">
import QuizOption from '@/components/QuizOption.vue'
import Button from '@/components/Button.vue'
import QuizContainer from '@/components/layout/QuizContainer.vue'
import { computed, ref } from 'vue'

const props = defineProps<{
  answers: {src: string, transform: string}[],
  response: number,
  state: string
}>()
const emit = defineEmits(['select'])

const selected = ref(-1)
// const state = ref('idle')

function select(index: number) {
  if (props.state === 'result') return

  selected.value = index
  emit('select', index)
}

function computedOutline(index: number) {
  if (selected.value !== index) {
    return 'none'
  }

  if (props.state !== 'result') {
    return 'default'
  }

  if (selected.value === props.response) {
    return 'success'
  }

  return 'error'
}

function computedMuted(index: number) {
  if (props.state === 'result') {
    return props.response !== index
  }

  if (props.state === 'selected') {
    return selected.value !== index
  }

  return false
}

function computedSize(index: number) {
  if (
    props.state === 'selected' && index === selected.value ||
    props.state === 'result' && index === props.response
  ) {
    return 'scale-105'
  }

  return ''
}

</script>

<template>
  <QuizContainer
    class="grid justify-items-center items-center gap-4"
    :size="state === 'result' ? 'fluid' : 'normal'"
  >
    <template v-for="(answer, index) in answers" :key="`answser-${index}`">
      <QuizOption
        v-bind="answer"
        :outline="computedOutline(index)"
        :muted="computedMuted(index)"
        :display="state"
        tabindex="0"
        :class="[computedSize(index)]"
        @focusin="select(index)"
      />
      <div v-if="index < answers.length - 1">VS</div>
    </template>
  </QuizContainer>
</template>

// src/components/Quiz.tsx

import { Component, createSignal, For, useContext } from 'solid-js';
import { QuizOption } from '~/components/QuizOption';
import { QuizContainer } from '~/components/layout/QuizContainer';

type QuizProps = {
  class?: string;
  answers: {src: string, transform: string}[];
  response: number;
  state: string;
  onSelect: (index: number) => void;
}

export const Quiz: Component<QuizProps> = (props) => {
  const [selected, setSelected] = createSignal(-1)

  function select(index: number) {
    if (props.state === 'result') return

    setSelected(index)
    props.onSelect(index)
  }

  function computedOutline(index: number) {
    if (selected() !== index) {
      return 'none'
    }

    if (props.state !== 'result') {
      return 'default'
    }

    if (selected() === props.response) {
      return 'success'
    }

    return 'error'
  }

  function computedMuted(index: number) {
    if (props.state === 'result') {
      return props.response !== index
    }

    if (props.state === 'selected') {
      return selected() !== index
    }

    return false
  }

  function computedSize(index: number) {
    if (
      props.state === 'selected' && index === selected() ||
      props.state === 'result' && index === props.response
    ) {
      return 'scale-105'
    }

    return ''
  }

  return <QuizContainer
    class={`grid justify-items-center items-center gap-4 ${props.class}`}
  >
    <For each={props.answers}>
      {(answer, index) => <QuizOption
        outline={computedOutline(index())}
        muted={computedMuted(index())}
        display={props.state}
        class={computedSize(index())}
        onFocus={() => select(index())}
        {...answer}
      />}
    </For>
  </QuizContainer>
}
